# Generated by Django 4.0.6 on 2022-09-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoFinal', '0002_dueño_marca_modelo_repuesto_delete_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
